apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Shared Apps
  - ../../apps/traefik.yaml
  - ../../apps/crossplane.yaml
  - ../../apps/velero.yaml
  
  # Shared Manifests
  - ../../manifests/crossplane-providers.yaml
  - ../../manifests/crossplane-configs.yaml
  # Note: cert-manager-issuers depends on cert-manager app being installed. 
  # Argo handles sync waves, so including it here is fine.
  - ../../manifests/cert-manager-issuers.yaml

  # GKE Specific Apps
  - ../../apps/cert-manager.yaml
