apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Shared Apps
  - ../../apps/traefik.yaml
  - ../../apps/crossplane.yaml
  - ../../apps/velero.yaml

  # Shared Manifests
  - ../../manifests/crossplane-providers.yaml
  - ../../manifests/crossplane-configs.yaml

  # Homelab Specific Apps
  - ../../apps/longhorn.yaml
  - ../../apps/garage.yaml

  # Homelab Specific Manifests
  - ../../manifests/cluster-identity-homelab.yaml
  
  # Exclusions
  # We do NOT include cert-manager.yaml here.

  # Ingress Routes
  - ../../ingress/argocd.yaml
  - ../../ingress/gitea-homelab.yaml
  - ../../ingress/longhorn.yaml
  - ../../ingress/garage.yaml
