apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "10" # Apply after Cert-Manager is ready
spec:
  acme:
    # You must replace this email
    email: admin@yggdrasil.cloud
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-gateway-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: traefik-gateway
            namespace: kube-system
            kind: Gateway
