
# GKE Environment Values

global:
  environment: gke
  domain: "siliconsaga.org"

# Layer 4: Fundamentals
traefik:
  serviceType: LoadBalancer
  enableDashboard: false

certManager:
  issuer: "letsencrypt-prod"
  email: "siliconsaga@gmail.com"

crossplane:
  provider: "gcp"
  bucketStorageClass: "standard"
