
# GKE Environment Values

global:
  environment: gke
  domain: "yggdrasil.cloud"

# Layer 4: Fundamentals
traefik:
  serviceType: LoadBalancer
  enableDashboard: false

certManager:
  issuer: "letsencrypt-prod"
  email: "admin@yggdrasil.cloud"

crossplane:
  provider: "gcp"
  bucketStorageClass: "standard"
