apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: layer4-fundamentals
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/nordri-admin/nordri.git'
    targetRevision: HEAD
    path: platform/fundamentals

  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
