apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/nordri-admin/nordri.git'
    path: platform/charts/garage
    targetRevision: HEAD
    helm:
      values: |
        persistence:
          enabled: true
          size: 10Gi
        s3Api:
          enabled: true
          port: 3900
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
